// import './example/basic-type.ts'
// import './example/symbol.ts'
// import './example/interface.ts'
// import './example/function'
// import './example/generics'
// import './example/es6-class-1.js'
// import './example/es6-class-2.js'
import './example/class'
// import './example/enumeration'
// import './example/interface-compatibility'
// import './example/advanced-type-1'
// import './example/advanced-type-2'